---
title: "Mztab import evaluation"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: true
    toc_depth: 3
    number_sections: true
date: "`r paste0('Evaluation date: ', format(Sys.time(), '%Y-%m-%d %H:%M:%S'))`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Evaluation summary

```{r main-table}
dt_source <- cbind(file = basename(all_files), 
                   jmztabm = factor(sapply(jmztabm_res, function(i) ifelse(is.null(attr(i, "status")), "success", "crash")), levels = c("crash", "silent failure", "success")),
                   import_df)

DT::datatable(dt_source,
              filter = "top",          
              options = list(
                pageLength = 20,         
                autoWidth = TRUE,         
                searchHighlight = TRUE,  
                dom = "Bfrtip",           
                buttons = c("copy", "csv")
              ),
              extensions = "Buttons"
) |> 
  DT::formatStyle(1L:ncol(import_df) + 2, # +2 because two first columns are file name and validator
                  backgroundColor = DT::styleEqual(levels = c("crash", "silent failure", "success"), 
                                                   values = c("#fc8d59", "grey83", "#91cf60"))) 
```

# Errors

```{r errors-sections, results='asis'}

all_text <- sapply(names(all_imports), function(ith_name) {
  all_reads <- all_imports[[ith_name]][["reads"]]
  resulting_class <- sapply(all_reads, class)
  all_errors <- all_reads[resulting_class == "try-error"]
  
  if(length(all_errors) > 0) {
    all_error_filenames <- basename(all_files)[resulting_class == "try-error"]
    
    c(paste0("\n\n## ", ith_name), sapply(1L:length(all_errors), function(ith_error) 
      paste0("\n\n### ", 
             all_error_filenames[ith_error], 
             "\n\nError message:",
             "\n\n<code>", all_errors[ith_error], "</code>")
    ))
  } else {
    ""
  }
})

cat(unlist(all_text), sep = "\n")
```

# About 

Source repository: https://github.com/michbur/reading-mzTab-into-R
